=== acanakoglu/GMQL-Tester/src/main/resources/configuration.xsd
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified"
           xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="gmql_new_test" type="gmql_new_testType"/>
    <xs:complexType name="root_folderType">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute type="xs:string" name="type" use="optional"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>
    <xs:complexType name="temp_folderType">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute type="xs:string" name="type" use="optional"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>
    <xs:complexType name="general_configType">
        <xs:choice maxOccurs="unbounded" minOccurs="0">
            <xs:element type="xs:string" name="execution_script"/>
            <xs:element type="root_folderType" name="root_folder"/>
            <xs:element type="temp_folderType" name="temp_folder">
                <xs:annotation>
                    <xs:documentation>not tested for hadoop</xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element type="xs:string" name="default_location_type"/>
        </xs:choice>
    </xs:complexType>
    <xs:complexType name="locationType">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute type="xs:string" name="type" use="optional"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>
    <xs:complexType name="datasetType">
        <xs:sequence>
            <xs:element type="locationType" name="location"/>
        </xs:sequence>
        <xs:attribute type="xs:string" name="name" use="optional"/>
    </xs:complexType>
    <xs:complexType name="datasetsType">
        <xs:sequence>
            <xs:element type="datasetType" name="dataset" maxOccurs="unbounded" minOccurs="0">
                <xs:unique name="unique-location-type">
                    <xs:selector xpath="location"/>
                    <xs:field xpath="@type"/>
                </xs:unique>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="tagsType">
        <xs:sequence>
            <xs:element type="xs:string" name="tag" maxOccurs="unbounded" minOccurs="0"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="queryType">
        <xs:sequence>
            <xs:element type="xs:string" name="description"/>
            <xs:element type="tagsType" name="tags"/>
            <xs:element type="xs:string" name="text"/>
        </xs:sequence>
        <xs:attribute type="xs:string" name="name" use="required"/>
        <xs:attribute name="time" use="required">
            <xs:simpleType>
                <xs:restriction base="xs:string">
                    <xs:enumeration value="short"/>
                    <xs:enumeration value="long"/>
                </xs:restriction>
            </xs:simpleType>
        </xs:attribute>
        <xs:attribute type="xs:string" name="target" use="optional"/>
    </xs:complexType>
    <xs:complexType name="queriesType">
        <xs:sequence>
            <xs:element type="queryType" name="query" maxOccurs="unbounded" minOccurs="0">
                <xs:annotation>
                    <xs:documentation>target is targeting operation if it is singleton, empty otherwiseTime should be
                        always defined
                    </xs:documentation>
                </xs:annotation>

            </xs:element>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="gmql_new_testType">
        <xs:sequence>
            <xs:element type="general_configType" name="general_config"/>
            <xs:element type="datasetsType" name="datasets">
                <xs:unique name="unique-dataset-name">
                    <xs:selector xpath="dataset"/>
                    <xs:field xpath="@name"/>
                </xs:unique>
            </xs:element>
            <xs:element type="queriesType" name="queries">
                <xs:unique name="unique-query-name">
                    <xs:selector xpath="query"/>
                    <xs:field xpath="@name"/>
                </xs:unique>
            </xs:element>

        </xs:sequence>
    </xs:complexType>

</xs:schema>

=== acanakoglu/GMQL-Tester/src/main/resources/arif_test.xml
<?xml version="1.0" encoding="UTF-8" standalone="no" ?>
<gmql_new_test xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
               xsi:noNamespaceSchemaLocation="configuration.xsd">
    <!--
    <general_config>
        <execution_script>/home/canakoglu/GMQL-test/GMQL/bin/GMQL-Submit</execution_script>
        <root_folder type="LOCAL">/home/canakoglu/GMQL-test/</root_folder>
        <temp_folder type="LOCAL">/tmp/gmql_testing/</temp_folder>
        <root_folder type="HADOOP">hdfs://</root_folder>
        <default_location_type>LOCAL</default_location_type>
    </general_config>
    -->
    <general_config>
        <execution_script>/Users/canakoglu/Documents/GMQL-test/GMQL/bin/GMQL-Submit</execution_script>
        <root_folder type="LOCAL">/Users/canakoglu/Documents/GMQL-test/</root_folder>
        <temp_folder type="LOCAL">/tmp/gmql_testing/</temp_folder>
        <!--not tested for hadoop-->
        <root_folder type="HADOOP">hdfs://</root_folder>
        <default_location_type>LOCAL</default_location_type>
    </general_config>
    <datasets>
        <dataset name="annotations_in">
            <location type="LOCAL">datasets/in/annotations</location>
        </dataset>
        <dataset name="annotations_out">
            <location type="LOCAL">datasets/out/annotations</location>
        </dataset>
        <dataset name="beds_in">
            <location type="LOCAL">datasets/in/beds</location>
        </dataset>
        <dataset name="beds_out">
            <location type="LOCAL">datasets/out/beds</location>
        </dataset>
        <dataset name="beds_out_no_result">
            <location type="LOCAL">datasets/out/beds_no_result</location>
        </dataset>
        <dataset name="beds_out_CTCF">
            <location type="LOCAL">datasets/out/beds_CTCF</location>
        </dataset>
        <dataset name="beds_out_ctcf">
            <location type="LOCAL">datasets/out/beds_ctcf2</location>
        </dataset>
        <dataset name="beds_out_not_CTCF">
            <location type="LOCAL">datasets/out/beds_not_CTCF</location>
        </dataset>
        <dataset name="beds_out_left_bigger_1000">
            <location type="LOCAL">datasets/out/beds_left_bigger_1000</location>
        </dataset>
        <dataset name="beds_out_left_bigger_1000_less_2000">
            <location type="LOCAL">datasets/out/beds_left_bigger_1000_less_2000</location>
        </dataset>
        <dataset name="beds_out_left_bigger_4000_less_1000">
            <location type="LOCAL">datasets/out/beds_left_bigger_4000_less_1000</location>
        </dataset>
        <dataset name="beds_out_right_less_0">
            <location type="LOCAL">datasets/out/beds_right_less_0</location>
        </dataset>
        <dataset name="beds_out_left_bigger_2000_right_less_4000">
            <location type="LOCAL">datasets/out/beds_left_bigger_2000_right_less_4000</location>
        </dataset>
        <dataset name="beds_out_left_bigger_2000_right_less_1000">
            <location type="LOCAL">datasets/out/beds_out_left_bigger_2000_right_less_1000</location>
        </dataset>
        <dataset name="beds_out_left_less_100_right_bigger_1200">
            <location type="LOCAL">datasets/out/beds_left_less_100_right_bigger_1200</location>
        </dataset>
        <dataset name="beds_out_average_1">
            <location type="LOCAL">datasets/out/beds_average_1</location>
        </dataset>
        <dataset name="beds_out_chr_1">
            <location type="LOCAL">datasets/out/beds_chr_1</location>
        </dataset>
        <dataset name="beds_out_strand_plus">
            <location type="LOCAL">datasets/out/beds_strand_plus</location>
        </dataset>
        <dataset name="beds_out_name_chr11">
            <location type="LOCAL">datasets/out/beds_name_chr11</location>
        </dataset>
        <dataset name="beds_out_zeroth_greater_0_7">
            <location type="LOCAL">datasets/out/beds_zeroth_greater_0_7</location>
        </dataset>
        <dataset name="beds_out_score_greater_0_7">
            <location type="LOCAL">datasets/out/beds_score_greater_0_7</location>
        </dataset>
        <dataset name="beds_out_strand_plus_first_gt_0_7">
            <location type="LOCAL">datasets/out/beds_strand_plus_first_gt_0_7</location>
        </dataset>
        <dataset name="beds_out_not_strand_plus">
            <location type="LOCAL">datasets/out/beds_not_strand_plus</location>
        </dataset>
        <dataset name="beds_out_chr_2_or_3">
            <location type="LOCAL">datasets/out/beds_chr_2_or_3</location>
        </dataset>
        <dataset name="beds_out_left_gt_10000_chr_2_or_3">
            <location type="LOCAL">datasets/out/beds_left_gt_10000_chr_2_or_3</location>
        </dataset>
        <dataset name="beds_out_not_chr_2_or_3">
            <location type="LOCAL">datasets/out/beds_not_chr_2_or_3</location>
        </dataset>
        <dataset name="beds_out_semijoin_CTCF">
            <location type="LOCAL">datasets/out/beds_semijoin_CTCF</location>
        </dataset>
        <dataset name="beds_out_semijoin_CTCF_region_chr1">
            <location type="LOCAL">datasets/out/beds_semijoin_CTCF_region_chr1</location>
        </dataset>
        <dataset name="beds_out_semijoin_organism_CTCF_region_chr1">
            <location type="LOCAL">datasets/out/beds_semijoin_organism_CTCF_region_chr1</location>
        </dataset>
        <dataset name="beds_out_semijoin_type_avg_CTCF_region_chr1">
            <location type="LOCAL">datasets/out/beds_out_semijoin_type_avg_CTCF_region_chr1</location>
        </dataset>
        <dataset name="beds_out_semijoin_BRD4">
            <location type="LOCAL">datasets/out/beds_semijoin_BRD4</location>
        </dataset>
        <dataset name="beds_out_semijoin_BRD4_region_chr1">
            <location type="LOCAL">datasets/out/beds_semijoin_BRD4_region_chr1</location>
        </dataset>
        <dataset name="beds_out_semijoin_organism_BRD4_region_chr1">
            <location type="LOCAL">datasets/out/beds_semijoin_organism_BRD4_region_chr1</location>
        </dataset>
        <dataset name="beds_out_semijoin_type_avg_BRD4_region_chr1">
            <location type="LOCAL">datasets/out/beds_out_semijoin_type_avg_BRD4_region_chr1</location>
        </dataset>
        <dataset name="cover_1_1">
            <location type="LOCAL">datasets/out/cover_1_1</location>
        </dataset>
        <dataset name="cover_1_2">
            <location type="LOCAL">datasets/out/cover_1_2</location>
        </dataset>
        <dataset name="cover_2_2">
            <location type="LOCAL">datasets/out/cover_2_2</location>
        </dataset>
        <dataset name="cover_1_ANY">
            <location type="LOCAL">datasets/out/cover_1_ANY</location>
        </dataset>
        <dataset name="cover_1_ALL">
            <location type="LOCAL">datasets/out/cover_1_ALL</location>
        </dataset>
        <dataset name="cover_ANY_ANY">
            <location type="LOCAL">datasets/out/cover_ANY_ANY</location>
        </dataset>
        <dataset name="cover_ANY_ALL">
            <location type="LOCAL">datasets/out/cover_ANY_ALL</location>
        </dataset>
        <dataset name="cover_ALL_ANY">
            <location type="LOCAL">datasets/out/cover_ALL_ANY</location>
        </dataset>
        <dataset name="join_distance_lt_1000_left">
            <location type="LOCAL">datasets/out/join_distance_lt_1000_left</location>
        </dataset>
        <dataset name="join_distance_lt_1000_contig">
            <location type="LOCAL">datasets/out/join_distance_lt_1000_contig</location>
        </dataset>
        <dataset name="join_distance_lt_1000_int">
            <location type="LOCAL">datasets/out/join_distance_lt_1000_int</location>
        </dataset>
        <dataset name="join_min_1_right">
            <location type="LOCAL">datasets/out/join_min_1_right</location>
        </dataset>
        <dataset name="join_distance_250_min_1_right">
            <location type="LOCAL">datasets/out/join_distance_250_min_1_right</location>
        </dataset>
        <dataset name="join_distance_250_1000_right">
            <location type="LOCAL">datasets/out/join_distance_250_1000_right</location>
        </dataset>
        <dataset name="join_dle_int_cell">
            <location type="LOCAL">datasets/out/join_dle_int_cell</location>
        </dataset>
        <dataset name="map">
            <location type="LOCAL">datasets/out/map</location>
        </dataset>
        <dataset name="map_joinby_antibody">
            <location type="LOCAL">datasets/out/map_joinby_antibody</location>
        </dataset>
        <dataset name="map_joinby_antibody_cell">
            <location type="LOCAL">datasets/out/map_joinby_antibody_cell</location>
        </dataset>
        <dataset name="map_max_score">
            <location type="LOCAL">datasets/out/map_max_score</location>
        </dataset>
        <dataset name="map_min_score">
            <location type="LOCAL">datasets/out/map_min_score</location>
        </dataset>
        <dataset name="map_sum_score">
            <location type="LOCAL">datasets/out/map_sum_score</location>
        </dataset>
        <dataset name="map_avg_score">
            <location type="LOCAL">datasets/out/map_avg_score</location>
        </dataset>
        <dataset name="map_bag_score">
            <location type="LOCAL">datasets/out/map_bag_score</location>
        </dataset>
        <dataset name="map_sum_min_max_score">
            <location type="LOCAL">datasets/out/map_sum_min_max_score</location>
        </dataset>
        <dataset name="map_min_max_score">
            <location type="LOCAL">datasets/out/map_min_max_score</location>
        </dataset>
        <dataset name="order_average">
            <location type="LOCAL">datasets/out/order_average</location>
        </dataset>
        <dataset name="order_average_asc">
            <location type="LOCAL">datasets/out/order_average_asc</location>
        </dataset>
